 version: '3'
 services:
   swarm1:
     build: ./swarmcontrol
     env_file:
      - ../scaling-variables-1.env
   swarm2:
     build: ./swarmcontrol
     env_file:
      - ../scaling-variables-2.env
   swarm3:
     build: ./swarmcontrol
     env_file:
      - ../scaling-variables-3.env
   swarm4:
     build: ./swarmcontrol
     env_file:
      - ../scaling-variables-4.env
   ansible1:
     build: ./ansible
     volumes:
      - ../hosts:/etc/hosts
      - ../id_rsa:/root/.ssh/id_rsa
     entrypoint:
      - ssh
      - johannes@swarm1-master
#     entrypoint:
#      - ansible
#      - -i
#      - ./swarm1-hosts
#      - all
#      - -a
#      - "uname -a"
#      - --become
